[tool.uv.workspace]
members = [
    "project/Ann",
    "project/CNN",
    "project/common"
]

# [tool.uv.workspace.dependencies]
# h5py = ">=3.14.0"
# imageio = ">=2.37.0"
# matplotlib = ">=3.10.7"
# opencv-python = ">=4.12.0.88"
# pandas = ">=2.3.3"
# pymonad = ">=2.4.0"
# pyside6 = ">=6.10.0"
# seaborn = ">=0.13.2"
# tabulate = ">=0.9.0"
# torch = ">=2.7.1"
# torchaudio = ">=2.7.1"
# torchvision = ">=0.22.1"
# tqdm = ">=4.67.1"
